baseURL = "https://example.com"
title = "Fuji Demo"
languageCode = "zh-Hans"
theme = "fuji"

hasCJKLanguage = true
disableKinds = ["RSS"]

summaryLength = 100 # Custom cummary length, add <!--more--> in post file to custom split point
paginate = 10

[permalinks]
  post = "/:filename/" # Custom post links, e.g. "/:year/:month/:title/"

[params]
  subTitle = "This is a Sub Title"

  # Bangumi image chart id
  # bgmImageChart = "000000"

  # Show scroll to top button
  scrollTop = true

  # License
  license = "知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议 (CC BY-NC-SA 4.0)"
  licenseLink = "http://creativecommons.org/licenses/by-nc-sa/4.0/"

  # Comments
  # utterances, see: https://utteranc.es/
  # cdnUtterancesJS = "https://utteranc.es/client.js"
  # utterancesRepo = "[ENTER REPO HERE]"
  # utterancesIssueTerm = "pathname"
  # utterancesTheme = "github-light"

  # Custom lazyload thumbnail
  cdnLazyloadSRC = "https://cdn.jsdelivr.net/gh/amzrk2/poal-jsdelivr/lazyload/dsr_loading.svg"
  # Custom css & js CDN
  cdnVanillaLazyloadJS = "https://cdn.jsdelivr.net/npm/vanilla-lazyload@15.1.1/dist/lazyload.min.js"
  cdnJQueryJS = "https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js"
  cdnProgessJS = "https://cdn.jsdelivr.net/npm/progressbar.js@1.1.0/dist/progressbar.min.js"

[markup]
  [markup.highlight]
    style = "monokailight"

[taxonomies]
  tag = "tags"

[menu]
  [[menu.nav]]
    name = "主页"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "归档"
    url = "/archive/"
    weight = 2
  [[menu.nav]]
    name = "关于"
    url = "/about/"
    weight = 3

  [[menu.link]]
    name = "GitHub"
    url = "https://github.com/amzrk2"
    weight = 1
  [[menu.link]]
    name = "哔哩哔哩"
    url = "https://space.bilibili.com/19767474"
    weight = 2
